In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
from keras import datasets 
(train_images,train_labels), (test_images,test_labels) = datasets.mnist.load_data()
train_images.shape

(60000, 28, 28)

In [3]:
test_images.shape

(10000, 28, 28)

In [4]:
import theano
from theano import tensor
a = tensor.dscalar('a')
b = tensor.dscalar('b')
res = a - b
func = theano.function([a,b],res)
func(30.5, 10.5)

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


array(20.)

In [5]:
!pip install theano

In [6]:
import numpy
import theano.tensor as T
from theano import function 
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x,y], z)
f(5, 7)

array(12.)

In [7]:

import theano.tensor as T
from theano import function 
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x,y], z)
f([[30, 50], [2, 3]], [[60, 70], [3, 4]] )

array([[ 90., 120.],
       [  5.,   7.]])

In [8]:
import torch 
print(torch.__version__)

1.12.1


In [9]:
a = torch.FloatTensor([2])
b = torch.FloatTensor([3])
a + b

tensor([5.])

In [10]:
matrix = torch.randn(3, 3)
matrix

tensor([[ 0.0912, -1.0858, -1.1417],
        [-0.4879,  0.3020, -0.8432],
        [ 2.5529,  0.3587,  0.8857]])

In [11]:
matrix.t()

tensor([[ 0.0912, -0.4879,  2.5529],
        [-1.0858,  0.3020,  0.3587],
        [-1.1417, -0.8432,  0.8857]])

In [12]:
import torch 
a = torch.Tensor([[1,2],[3,4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [13]:
print(a**2)

tensor([[ 1.,  4.],
        [ 9., 16.]])


In [15]:
# Tensorflow and Keras Program
import tensorflow as tf 
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')
x = np.array([1.0, 2.0, 3.0, 4.0, 6.0, 7.0], dtype = float) # features
y = np.array([4.0, 6.0, 8.0, 10.0, 14.0, 16.0], dtype = float) # labels

In [16]:
history = model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 655ms/step - loss: 135.4401
Epoch 2/50
1/1 [==============================] - 0s 8ms/step - loss: 49.2696
Epoch 3/50
1/1 [==============================] - 0s 9ms/step - loss: 18.1261
Epoch 4/50
1/1 [==============================] - 0s 12ms/step - loss: 6.8684
Epoch 5/50
1/1 [==============================] - 0s 14ms/step - loss: 2.7973
Epoch 6/50
1/1 [==============================] - 0s 8ms/step - loss: 1.3232
Epoch 7/50
1/1 [==============================] - 0s 8ms/step - loss: 0.7877
Epoch 8/50
1/1 [==============================] - 0s 13ms/step - loss: 0.5914
Epoch 9/50
1/1 [==============================] - 0s 11ms/step - loss: 0.5177
Epoch 10/50
1/1 [==============================] - 0s 14ms/step - loss: 0.4884
Epoch 11/50
1/1 [==============================] - 0s 7ms/step - loss: 0.4751
Epoch 12/50
1/1 [==============================] - 0s 7ms/step - loss: 0.4676
Epoch 13/50
1/1 [==============================] - 0s 7ms/step